version: '3'
services:
  education-mysql:
    image: mysql
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=education-api
      - MYSQL_ROOT_PASSWORD=education